### ISSUE TITLE
playback error from openmeta library or search

### ISSUE THREAD

**Issue by ry0240** [ruinernin/foxystreams#13]
I keep getting an error when attempting to select a link from openmeta or the search, but the list category plays most links just fine. 

```
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'infos'
                                            Traceback (most recent call last):
                                              File "C:\Users\Ryan\AppData\Roaming\Kodi\addons\plugin.video.foxystreams\addon.py", line 420, in <module>
                                                router.run()
                                              File "C:\Users\Ryan\AppData\Roaming\Kodi\addons\plugin.video.foxystreams\resources\lib\router.py", line 146, in run
                                                func(**kwargs)
                                              File "C:\Users\Ryan\AppData\Roaming\Kodi\addons\plugin.video.foxystreams\addon.py", line 383, in root
                                                fn_filter=_fn_filter)
                                              File "C:\Users\Ryan\AppData\Roaming\Kodi\addons\plugin.video.foxystreams\resources\lib\foxydebrid\debrid.py", line 402, in resolve_url
                                                url = unlock['infos']['link']
                                            KeyError: 'infos'
                                            -->End of Python script error report<--
```

**Comment by ruinernin** [comment]
Are you using AllDebrid? I had started adding support for this service but stopped working on it as it was a faff. I've been meaning to remove the code.

If you're not make sure AllDebrid is disabled in settings because that error is coming from AllDebrid.

**Comment by ry0240** [comment]
Ok yeah I'm using alldebrid

**Comment by ruinernin** [comment]
Apologies all I can suggest is to use another piece of software with support for AllDebrid or use a supported provider. I won't be able to fix this as I no longer have an AllDebrid account.
