### ISSUE TITLE
Fresh install Errors

### ISSUE THREAD

**Issue by mrXoo** [ruinernin/foxystreams#23]
Hi there,

Im trying to install foxystreams and foxymeta on a fresh install but getting some errors
[01_KODI.log](https://github.com/ruinernin/foxystreams/files/5790115/01_KODI.log)

**Comment by mrXoo** [comment]
this is what I have not sure if its the same

20:02:50.019 T:14872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmcaddon.Addon' object has no attribute 'getSettingBool'
                                            Traceback (most recent call last):
                                              File "C:\Users\ED\Documents\KODI\KRYPTON\Kodi\portable_data\addons\plugin.video.foxystreams\launcher.py", line 4, in <module>
                                                addon.run(*sys.argv[:3])
                                              File "C:\Users\ED\Documents\KODI\KRYPTON\Kodi\portable_data\addons\plugin.video.foxystreams\addon.py", line 413, in run
                                                for provider in get_user_debrid_providers():
                                              File "C:\Users\ED\Documents\KODI\KRYPTON\Kodi\portable_data\addons\plugin.video.foxystreams\addon.py", line 112, in get_user_debrid_providers
                                                if router.addon.getSettingBool(
                                            AttributeError: 'xbmcaddon.Addon' object has no attribute 'getSettingBool'
                                            -->End of Python script error report<--
