### ISSUE TITLE
Play cached item from "List" error

### ISSUE THREAD

**Issue by DaisyF8** [ruinernin/foxystreams#8]
Hi, (nice addon by the way)

Directly in your addon  :

when in "List" I click on a green link I get "Foxystreams Error" (see log below)

while when I'm in "Downloads" green links play just fine.

Am I misunderstanding the way your addon is supposed to work ? I don't always want to use OpenMeta.  Just browsing "List" or search results in your addon and clicking a green link would be nice.

This is the error in the log :

`
2019-10-25 15:27:47.827 T:140380275554048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'str' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/gerd/.kodi/addons/plugin.video.foxystreams/addon.py", line 332, in <module>
                                                main()
                                              File "/home/gerd/.kodi/addons/plugin.video.foxystreams/addon.py", line 212, in main
                                                url = user_debrid.resolve_url(args['magnet'], args['cache'])
                                              File "/home/gerd/.kodi/addons/plugin.video.foxystreams/resources/lib/foxydebrid/debrid.py", line 326, in resolve_url
                                                return self.cached_content(magnet, fn_filter)[-1]['link']
                                              File "/home/gerd/.kodi/addons/plugin.video.foxystreams/resources/lib/foxydebrid/debrid.py", line 321, in cached_content
                                                content = [item for item in content if fn_filter(item['path'])]
                                            TypeError: 'str' object is not callable
                                            -->End of Python script error report<--
2019-10-25 15:27:47.953 T:140383591606976   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.foxystreams/?magnet=magnet%3A%3Fxt%3Durn%3Abtih%3A4d1018c88d4dd61365b3dec306c39cc34280dc9d%26dn%3DSeth.Meyers.2019.10.24.Willem.Dafoe.WEB.h264-TBS%255Brartv%255D%26tr%3Dhttp%253A%252F%252Ftracker.trackerfix.com%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2710%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2710%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337%252Fannounce&cache=True&mode=vid]
`

and this is how a link in "Downloads" gets played

`2019-10-25 15:30:10.964 T:140383591606976  NOTICE: VideoPlayer::OpenFile: *REMOVED*
2019-10-25 15:30:11.236 T:140380796282624  NOTICE: Creating InputStream
2019-10-25 15:30:11.989 T:140380796282624  NOTICE: Creating Demuxer
2019-10-25 15:30:12.253 T:140380796282624  NOTICE: Opening stream: 0 source: 256`

**Comment by ruinernin** [comment]
That shouldn't happen. Thanks for pointing it out! I'll get it fixed today or tomorrow.

**Comment by ruinernin** [comment]
Thanks again for opening the issue, a fix has been commited in ca5f94470974d6f3a0a473d162c26f7566210e53 and the version has been bumped. You should be able to update and hopefully it's working again.

This was an issue when using Premiumize as a provider and I had failed to test this use case after I cleaned up some code recently. The log data was very helpful in tracking this down quickly, thanks! (I edited the comment to remove a link I believe is unique to your account).

**Comment by DaisyF8** [comment]
Thx for cleaning my log. I looked it through but missed it.

And thanks for the fix :)
